name: docker_build
on: 
  push:
    branches:
      - dev
jobs:
 docker_info:
   runs-on: windows
   steps:
   - name: docker_version
     run: docker --version
 my-job:
    runs-on: amazonlinux:latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        run: cat /etc/os-release
